server:
  port: 8091

spring:
  application:
    name: redirect
  main:
    log-startup-info: true

jwt.public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwYIh0t3ych3yQHVnU52H60WRUuzKZWiv80ocVkBZi/wL8C+aGoyTpZQ46Kx3gmjx9igNuNPMf8ffQjwsfHH2lN4dDM4/oS54wDbWu/6ZdqDWZvIp2kxs4qq3tGiYWwRoB/Q/xc7j2f2pcM0J2Nm9NTKIlVcnYDA4hm/iwE/rawnKEa8dgS99GQy+FJ75Qj0vnzM/xojc72BqJ7HSWmWBN2o3cu8riz4AQD6nhWi9hAzqKMfp+dtR0gixA6IFx2dEf6sjcg6rfYXNj1tClJAFd5DVFDmmtVxrrAQRgsZtUWR1sdgdNC0NfevUV7f2DDhAdlbxb+tGCn5wsM56d3o5bwIDAQAB

services:
  auth: http://localhost:8092/api/v1
  redirect: http://localhost:8093/api/v1

management:
  info:
    git:
      mode: "FULL"
  endpoints:
    web:
      exposure:
        include: "health,info"

logging:
  level:
    root: INFO
    ru.otus.gateway: INFO